### PR TITLE
Add bitarray 2.7.3 package for Deltacode upgrade

### PR DESCRIPTION
**Pull request by arnav-mandal1234**
* ran this command `python3 etc/scripts/fetch_thirdparty.py --wheels --sdists --spec bitarray==2.7.3 --dest ../temp/`
* Followed the steps in https://github.com/nexB/thirdparty-packages#readme

### CODE REVIEW

**Comment by arnav-mandal1234** [comment]
@pombredanne @AyanSinhaMahapatra @JonoYang can you please review?

**Review by AyanSinhaMahapatra — APPROVED** [review]
Thanks @arnav-mandal1234 , looks good to me!

LGTM!

**Comment by AyanSinhaMahapatra** [comment]
Merging this! Thanks++

**Comment by AyanSinhaMahapatra** [comment]
@arnav-mandal1234 one small nit for future:

Add references to the issue you are solving in the commit, like this:

```
Add bitarray 2.7.3 package for Deltacode upgrade #7

Reference: https://github.com/nexB/thirdparty-packages/issues/7
Signed-off-by: Arnav Mandal <arnav.mandal1234@gmail.com>
```

And also add in the PR description:
```
Closes/Fixes #7
```
See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

So we have links from the PR to the issue, and this closes automatically after merging!

**Pull request merged**
